### ISSUE TITLE
stop and go

### ISSUE THREAD

**Issue by morwic** [mobehun/BraveTechnology#3]
on a x2 Xeon with 64gb of ram, and the pack just keeps stopping every 30 sec ? only pack that does this ?

**Comment by mobehun** [comment]
Do you mean lag-spikes?

**Comment by morwic** [comment]
yes sir

**Comment by mobehun** [comment]
So... That's a server right? As far as I know it's caused by players. What I mean is that when you build your base somewhere and just keep putting down new machines, the block updates will cause lag. Other problem could be when someone goes exploring in new, ungenerated areas. 
To be honest the recommended amount of allocated ram would be over 4 GB (I'm using 6 in my testing environment and still get lag-spikes from time to time)

**Comment by morwic** [comment]
i see nee game on a local system i have 6 gb on the pack now ? hum..

Thank you,
     Morwic

**Comment by mobehun** [comment]
Yes. Something like that. If that doesn't help start a new issue and I'll look deeper into it.
